### ISSUE TITLE
Merlin Error: Unbound module Llvm

### ISSUE THREAD

**Issue by luxroot** [prosyslab-classroom/is893-2020-fall#19]
Maybe it's trivial thing to someone, but I'm annoyed with error message says "Unbound module Llvm"
To solve this, we need to edit `src/.merlin` file

and add a line
`PKG llvm` right after `EXCLUDE_QUERY_DIR`

After editing `src/.merlin` like this
```
EXCLUDE_QUERY_DIR
PKG llvm
blah blah ~
```
We can make most of some type-checking, and auto-completion feature for Llvm module. (which is a feature of merlin package)
The most important thing is that we're free from error messages.

Sorry for making an issue late at night.

**Comment by tomtomjhj** [comment]
I've been using [ocaml-lsp](https://github.com/ocaml/ocaml-lsp/) (which uses merlin under the hood) and that has never been an issue for me. What do you use for editing?

**Comment by luxroot** [comment]
> I've been using [ocaml-lsp](https://github.com/ocaml/ocaml-lsp/) (which uses merlin under the hood) and that has never been an issue for me. What do you use for editing?

I'm using vim and [dotfiles of professor](https://github.com/KihongHeo/environment). Maybe I'm the only one having issues..

**Comment by KihongHeo** [comment]
Can you first double check that you are using the correct OCaml switch (`opam switch`)?
Also run `make` first.

Let me know if you still have the same issue.

**Comment by luxroot** [comment]
It seems like I haven't run `make` at first time. My bad..
