### ISSUE TITLE
Pre-class notice

### ISSUE THREAD

**Issue by myojoonkil** [prosyslab-classroom/is893-2020-fall#3]
Hi all, 

Please follow the instructions below.

1. Please submit the google form to share your GitHub ID. 
https://forms.gle/oKQ1kmc6k1PFW6rA6

2. We matched the VM number for each student.
The ip address and port number of the vm are attached to the Excel file. [IS893_vm.xlsx](https://github.com/prosyslab-classroom/is893-2020-fall/files/5146426/IS893_vm.xlsx)
We already have pre-requisite installed in the docker.
So, please check if your VM works well and ask TA if there is any problem.
You can change the access password freely :)

|VM no.|Student name|
|-------|--------------|
|1|이대진|
|2|신명근|
|3|정재황|
|4|홍재민|
|5|강우석|
|6|김현수|
|7|정승준|
|8|류혜원|

**Comment by KihongHeo** [comment]
Notice that this VM is not mandatory but for those who have troubles in setup.
Feel free to use whatever environment you want: your local machine, provided [docerker file](https://github.com/prosyslab-classroom/is893-2020-fall/blob/master/docker/Dockerfile), or VM.
You can follow the commands in the docker file when you setup your local environment.
