### ISSUE TITLE
The term "midnight"

### ISSUE THREAD

**Issue by luxroot** [prosyslab-classroom/is893-2020-fall#34]
Homework 4's due is 10.15 midnight.
I'm curious that 10.15 midnight means 1 or 2.
```
   1    2
14 | 15 | 16
   ^    ^
```

I think I'm not the only one who is confused with term midnight [https://english.stackexchange.com/questions/6459/how-should-midnight-on-be-interpreted](https://english.stackexchange.com/questions/6459/how-should-midnight-on-be-interpreted)

So, how about using explicit time visualization like [https://www.timeanddate.com/countdown/generic?iso=20201016T00&p0=3999&msg=Homework+4+Due&font=cursive](https://www.timeanddate.com/countdown/generic?iso=20201016T00&p0=3999&msg=Homework+4+Due&font=cursive)
which can be made here [https://www.timeanddate.com/countdown/create](https://www.timeanddate.com/countdown/create)

**Comment by KihongHeo** [comment]
For all homework in this class, I mean 2. 
23:59:59

**Comment by luxroot** [comment]
Thanks for quick reply!
