### ISSUE TITLE
Paper bidding 

### ISSUE THREAD

**Issue by KihongHeo** [prosyslab-classroom/is893-2020-fall#4]
Hi all,

Please fill this time table with your choice of papers: https://docs.google.com/spreadsheets/d/1XWGdLnSZEkEaK1olUEcjb9SKhbfpW5-roQ6asPTfBhE/edit?usp=sharing

**Comment by KihongHeo** [comment]
Updated the URL (editable).

**Comment by KihongHeo** [comment]
Each presentation will be 30 min.

**Comment by KihongHeo** [comment]
Please make sure your presentation is consistent with the topic of each part. (e.g., @daejin1592)

**Comment by daejin1592** [comment]
I just fixed the links. 
Sorry for late. :(
