### ISSUE TITLE
some bugs in hw5 template

### ISSUE THREAD

**Issue by tomtomjhj** [prosyslab-classroom/is893-2020-fall#41]
* `tests/dune` has some unused rules for "interval" domain tests and it passes domain type (sign/interval) to `analyzer` binary.
* `Table.init` doesn't handle phi nodes.

**Comment by KihongHeo** [comment]
Thanks for reporting.

I made patches.

http://elvis01.kaist.ac.kr/kihong/course/0001-fix-test.patch
http://elvis01.kaist.ac.kr/kihong/course/0002-fix-init.patch

You can try `git apply` or so.

I fixed the template repo. For other students who haven't forked yet, you will get a fixed repo directly.

**Comment by luxroot** [comment]
Seems to be a typo, isn't this issue is about HW 5?
