### ISSUE TITLE
[Question]Ocaml grammar  recursive function usage typo(?)

### ISSUE THREAD

**Issue by sjoon2455** [prosyslab-classroom/is893-2020-fall#6]
Hi, while following codes in the first slide about Ocaml I noticed this(slide 12/57):

![image](https://user-images.githubusercontent.com/38874408/91789817-5e2d8d00-ec4a-11ea-8064-c529ed202a1d.png)

When _pow()_ gets defined it takes two inputs, _x_ and _y_. But when it's used in the function body (of itself), it gets a single input, _y-1_. Is this a typo? If so, how should it get fixed? I tried _pow(x, y-1)_ instead but yields syntax error anyways. Please help!

Additional question,
how can I put a label on an issue?

**Comment by hyunsukimsokcho** [comment]
I suggest trying
```ocaml
let rec pow x y = if y=0 then 1 else x * (pow x (y - 1))
```

I think it is indeed a typo.

**Comment by KihongHeo** [comment]
Hi,

Nice catch. Thit is a typo. Let me fix it. You should do as Hyunsu did.

`pow (x, y-1)` and `pow x (y-1)` are slightly different. Let me simplify the example:
```
let f (x,y) = x + y
let g x y = x + y
```
`f` takes *one* argument whose type is a tuple and returns an integer.
`g` takes *one* argument whose type is an integer and returns a *function* whose type is `int -> int`. This returned function can be applicable to another integer: (verbosely) `((g 1) 2)`. This kind of function is called a *curried*  function. For the details, see this document (https://dev.realworldocaml.org/variables-and-functions.html) and find "curried".

**Comment by sjoon2455** [comment]
Thank you!
